### PR TITLE
Preparing release 0.7.0

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by tgoodlet** [comment]
@nicoddemus So I just merge and that's it?

**Comment by nicoddemus** [comment]
Nope hold on

**Comment by nicoddemus** [comment]
I found a problem with the script, it is messing line endings because I'm on Windows

**Comment by nicoddemus** [comment]
And to answer your question: actually the last step, after approvals, is to push a tag to the last commit of this PR; this will trigger the deploy. After that we can merge. 😁

**Pull request closed without merging**
