### PR TITLE
Drop support for EOL Python 2.6 & 3.3

### PR DESCRIPTION
**Pull request by hugovk**
Fixes https://github.com/pytest-dev/pluggy/issues/92.

### CODE REVIEW

**Comment by tgoodlet** [comment]
@hugovk looks good 👍 

Do you mind tagging your commit message with `Resolves #92` such that when we merge the issue will auto-close?

**Comment by hugovk** [comment]
I certainly can do, but "Fixes #92" in the PR message should do the same:

https://help.github.com/articles/closing-issues-using-keywords/

Would you like the commit message updating?

**Comment by nicoddemus** [comment]
@hugovk also please add a new CHANGELOG entry, I think the next version should be `0.6` because of this.

**Comment by hugovk** [comment]
CHANGELOG updated.

Should we also drop EOL Python 3.3?

3.3 was dropped from pytest's features branch at the same time as 2.6: https://github.com/pytest-dev/pytest/pull/2822.

**Comment by tgoodlet** [comment]
>I certainly can do, but "Fixes #92" in the PR message should do the same:

Cool, then I don't care too much if it's git history.

>3.3 was dropped from pytest's features branch at the same time as 2.6: pytest-dev/pytest#2822.

I'm 👍 on this but wait to see what @nicoddemus and @RonnyPfannschmidt say.

**Comment by nicoddemus** [comment]
> Should we also drop EOL Python 3.3?

Yes please. 😁

**Comment by hugovk** [comment]
Updated to drop 3.3 as well.

**Pull request merged**
