### PR TITLE
Split into modules

### PR DESCRIPTION
**Pull request by tgoodlet**
This is to replace #101 by @RonnyPfannschmidt.

The differences include:
- rebased onto master incorporating the latest changes
- maintaining as much of the history as possible in what was `pluggy.PluginManager` (where most of the non-@hpk42 contributions seemed to be) by moving `pluggy.__init__.py` -> `pluggy.manager` and pulling out internals from that module into other new modules
- ensuring the test suite can run successfully between each incremental change (commit) such that each patch is a logical change set
- avoiding the #101 proposed `parse_funcs` module (it's unecessary when it's a utility function used only by the code in `hooks.py`)

Let me know what you guys think!

### CODE REVIEW

**Comment by nicoddemus** [comment]
The split seems sensible to me... we just have to take a look at the test failures with pytest master.

**Comment by tgoodlet** [comment]
>we just have to take a look at the test failures with pytest master

Yeah gonna try and reproduce locally with `tox`.
It's also weird that my latest for push hasn't shown up here in GH...

**Comment by tgoodlet** [comment]
@nicoddemus hah! Think I figured it out.
The first time you run the `pytest` integration tests they fail because on install I think the old `pluggy` package is being used somehow. The failure is consistent as long as I pass `-r` to `tox`.

My original guess would be that the `_PYTEST_SETUP_SKIP_PLUGGY_DEP` isn't being set early enough since when I hop in the debugger in fact `pytest` is using the `pluggy` installed in the `virtualenv` instead of the sources. However, inspecting that env var shows it **is** set by the time it hits the import error?

Any ideas?

**Comment by tgoodlet** [comment]
Did something change in `tox` regarding when/how the project under test is installed?

**Comment by nicoddemus** [comment]
@tgoodlet a test of your theory would be to set `_PYTEST_SETUP_SKIP_PLUGGY_DEP` in the `.travis.yml` file manually before calling `tox`; if that changes the outcome then we know your hypothesis holds.

**Comment by tgoodlet** [comment]
My [theory failed](https://travis-ci.org/pytest-dev/pluggy/jobs/326142225)...

I'm going to try and hook into my local `pytest` code and see what's going on.

**Comment by tgoodlet** [comment]
Oh man @nicoddemus 🤦‍♂️ 
You're gonna laugh at me...

**Comment by nicoddemus** [comment]
What is it? 😛

**Comment by tgoodlet** [comment]
minor version bump was needed to get `pip` to install the sources...

**Comment by nicoddemus** [comment]
Oh hehehe makes sense! Glad it was something simple then! 😁

**Comment by tgoodlet** [comment]
Alright now I just need some approvals 👍

**Comment by nicoddemus** [comment]
Nice work, thanks @tgoodlet!

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt @hpk42 you two ok with this?

**Pull request merged**
