### PR TITLE
0.5.1 patch release

### LINKED ISSUE #68: regression for firstresult hook without implementation
https://github.com/devpi/devpi/issues/458

is triggered by https://github.com/pytest-dev/pluggy/pull/58/files#diff-85f4be4e30ec3b4f3d53843b24d72141R109

@tgoodlet i beleive a test is needed for those edge behaviours

### PR DESCRIPTION
**Pull request by tgoodlet**
Fixes #68 and get's #69 into the wild stat!

### CODE REVIEW

**Comment by tgoodlet** [comment]
[it's up](https://pypi.org/project/pluggy/)!

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt @nicoddemus I meant to ask, who's responsible for the conda package?

**Comment by RonnyPfannschmidt** [comment]
i'm relatively certain, that i am not ^^

@nicoddemus im wondering about having a git repo on pytest-dev and a bit that will update it for eachrelease

**Comment by nicoddemus** [comment]
> I meant to ask, who's responsible for the conda package?

For pytest and a few other plugins it's me. I just added myself as maintainer of the pluggy package along with @JohnGreeley (conda-forge/staged-recipes#3862). 

>  im wondering about having a git repo on pytest-dev and a bit that will update it for eachrelease

You mean a repository responsible for updating the conda packages automatically? Sounds like a good idea. Are you thinking of something along the lines of:

1. A repo containing submodules of the pytest-dev related feedstocks repositories (forks under pytest-dev).
2. A script which runs daily on Travis that updates the recipes with the latest versions from PyPI and automatically opens PRs.

**Comment by nicoddemus** [comment]
Thanks guys for tackling this so promptly btw, and sorry for not being able to respond earlier.

**Pull request merged**
