### PR TITLE
WIP:  Factor out pkg_resources for importlib_metadata

### PR DESCRIPTION
**Pull request by asottile**
Using a hacked up version of pytest this speeds up `pytest --help` by 26%:

```diff
diff --git a/src/_pytest/assertion/rewrite.py b/src/_pytest/assertion/rewrite.py
index 301bdedc..cdde4ab6 100644
--- a/src/_pytest/assertion/rewrite.py
+++ b/src/_pytest/assertion/rewrite.py
@@ -316,6 +316,7 @@ class AssertionRewritingHook(object):
         Ensure package resources can be loaded from this loader. May be called
         multiple times, as the operation is idempotent.
         """
+        return
         try:
             import pkg_resources
 
diff --git a/src/_pytest/config/__init__.py b/src/_pytest/config/__init__.py
index 3943f847..0db4d254 100644
--- a/src/_pytest/config/__init__.py
+++ b/src/_pytest/config/__init__.py
@@ -14,7 +14,6 @@ import warnings
 
 import py
 import six
-from pkg_resources import parse_version
 from pluggy import HookimplMarker
 from pluggy import HookspecMarker
 from pluggy import PluginManager
@@ -739,6 +738,7 @@ class Config(object):
         modules or packages in the distribution package for
         all pytest plugins.
         """
+        return
         import pkg_resources
 
         self.pluginmanager.rewrite_hook = hook
@@ -814,6 +814,7 @@ class Config(object):
                 raise
 
     def _checkversion(self):
+        return
         import pytest
 
         minver = self.inicfg.get("minversion", None)
diff --git a/src/_pytest/outcomes.py b/src/_pytest/outcomes.py
index 14c6e9ab..dfbcb152 100644
--- a/src/_pytest/outcomes.py
+++ b/src/_pytest/outcomes.py
@@ -173,6 +173,7 @@ def importorskip(modname, minversion=None, reason=None):
     verattr = getattr(mod, "__version__", None)
     if minversion is not None:
         try:
+            raise Skipped('wat')
             from pkg_resources import parse_version as pv
         except ImportError:
             raise Skipped(
```

(Using **_best of 5_**)

```console
$ # before
$ time pytest --help > /dev/null

real	0m0.377s
user	0m0.362s
sys	0m0.012s
```

```console
$ # after
$ time pytest --help > /dev/null

real	0m0.276s
user	0m0.253s
sys	0m0.016s
```

### CODE REVIEW

**Comment by nicoddemus** [comment]
This is definitely interesting. 👍 

Did you manage to make all tests pass locally for you with your hacked version?

**Comment by asottile** [comment]
> This is definitely interesting. 
> 
> Did you manage to make all tests pass locally for you with your hacked pytest?

I didn't try to get the pytest suite working, only had enough time to stub out the other things using pkg_resources. I can take a stab at a full non-hacked working pytest later

**Comment by nicoddemus** [comment]
Nice, let's see if we can get rid of `pkg_resources` then. 👍 

It would be a great `0.9` release together with `pytest 4.3`.

**Comment by asottile** [comment]
don't ship this just yet, I think `importlib-metadata` is the better approach than `entrypoints` -- at least for pytests's sake

**Comment by asottile** [comment]
this is blocked on a 0.9 release of importlib-metadata

**Pull request closed without merging**
