### PR TITLE
Preparing release 0.11.1

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by hroncok** [comment]
Before this is released, plese see https://github.com/pytest-dev/pluggy/pull/210#issuecomment-492712324

**Comment by nicoddemus** [comment]
Rebased. 👍

**Comment by goodboy** [comment]
@nicoddemus we've got that [benchmark suite](https://github.com/pytest-dev/pluggy/blob/master/tox.ini#L18) that could be used to eyeball for slowdowns?

**Comment by nicoddemus** [comment]
Here are the benchmarks, what do you guys think?

https://gist.github.com/nicoddemus/105e7bd20b9699ac5330968fadfc5b67

Also just realized this should be `0.12.0` because of the new dependency.

**Comment by goodboy** [comment]
@nicoddemus slightly faster on `master`?

Wait, `0.11.1` is the release you just made - so we got a slight slow down I guess?
If that's the case then this is what we expect yes?

**Comment by nicoddemus** [comment]
`0.11.1` is this branch (not yet released), so yeah we got a little slower. Do people think this is a blocker and we should revert the patch? IMHO no, but would like to hear others' opinions.

**Comment by nicoddemus** [comment]
Gentle ping @goodboy and @asottile 😁

**Comment by goodboy** [comment]
@nicoddemus I think it's probably fine; we're still getting most of our speedups by dropping the old multicall stuff.

If they reverted that deprecated in `cpython` I wonder if it's worth all this effort though.

**Comment by hroncok** [comment]
> If they reverted that deprecation in cpython I wonder if it's worth all this effort though.

Good question. Does the new code make it more readable or maintainable?

**Comment by asottile** [comment]
With the undeprecation I'm not sure moving to Signature is buying us much -- I don't particularly care either way though so: +0

**Comment by nicoddemus** [comment]
> Good question. Does the new code make it more readable or maintainable?

TBH it is a little more complicated, but only because we still need to maintain two APIs: `inspect.getsignature` and `inspect.Signature`, which are quite different. It is also slightly slower.

Given that the deprecation is removed, I think it would be a good idea to revert the patch (if @hroncok doesn't mind, of course).

**Comment by hroncok** [comment]
My only motivation was to get rid of the warning. Of course I don't mind.

But please keep the added test.

**Comment by nicoddemus** [comment]
Thanks @hroncok! Opened https://github.com/pytest-dev/pluggy/pull/214.

**Pull request closed without merging**
