### PR TITLE
Preparing release 1.5.0

### PR DESCRIPTION
**Pull request by bluetech**

### CODE REVIEW

**Review by RonnyPfannschmidt — APPROVED** [review]

**Comment by bluetech** [comment]
The deploy job failed with this error:

> ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
>         User 'goodboy' does not have a verified primary email address. Please  
>         add a verified primary email before attempting to upload to PyPI. See  
>         https://pypi.org/help/#verified-email for more information.

@nicoddemus @RonnyPfannschmidt could one of you replace the pypi token with a new one? (I do not have pypi permissions myself)

**Comment by RonnyPfannschmidt** [comment]
I'll add oidc configuration as soon as I get back to a computer

**Comment by RonnyPfannschmidt** [comment]
as oidc needs changes, i uploaded with a new token that i will delete now

**Comment by bluetech** [comment]
Thanks @RonnyPfannschmidt!

**Pull request merged**
