### PR TITLE
Preparing release 0.13.0

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by asottile** [comment]
primarily to avoid https://gitlab.com/python-devs/importlib_metadata/issues/87

**Comment by asottile** [comment]
due to circular dependencies, the 3.8-dev build for this PR is failing due to `tox -> importlib-metadata`, I believe that's ok to ignore

**Comment by hroncok** [comment]
Unless https://github.com/tox-dev/tox/pull/1368 is released, it will continue to fail.

**Comment by asottile** [comment]
tox 3.14 includes that change

**Pull request merged**
