### PR TITLE
Moving to new style classes (object inheritance) - Issue #44

### PR DESCRIPTION
**Pull request by MichalTHEDUDE**
Adding to all classes inheritance from `object` class.

All test green, excepts for Interpreters:
- python2.6
- python3.4
- pypy

as I don't have them. 
Hope it isn't an issue :)

### CODE REVIEW

**Comment by nicoddemus** [comment]
Not at all, we have AppVeyor and Travis to test across all interpreters and configurations required. Thanks again!

**Comment by hpk42** [comment]
Is there any particular reason to move to new style classes? I typically try to use a subset of python such that it doesn't matter if a class derives from object.  In fact i rarely use inheritance anyway :)

**Comment by nicoddemus** [comment]
This has been discussed in #2147, old-style classes introduce subtle differences that, granted, are hard to come by, but since it is simple to make it consistent across all versions we decided to just make them all new-style explicitly.

**Comment by tgoodlet** [comment]
@hpk42 @nicoddemus it's an interesting point too because [in py3 old-style don't exist any more](https://docs.python.org/2/reference/datamodel.html#new-style-and-classic-classes) and [the syntax is equivalent](https://docs.python.org/3.6/reference/compound_stmts.html#class).

**Comment by hpk42** [comment]
oki.  could you directly commit a changelog entry?

**Comment by tgoodlet** [comment]
oh yey and now I have to rebase everything lolz

**Pull request merged**
