### PR TITLE
Preparing release 0.12.0

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Feel free to announce this on Twitter if you like! 🎆

**Comment by nicoddemus** [comment]
You might mention that pytest 4.5 users will get speedup this automatically (https://github.com/pytest-dev/pytest/blob/master/setup.py#L17)

**Comment by asottile** [comment]
pytest 4.5 users won't get the speedup just yet as pytest uses `pkg_resources` itself -- though I did make sure that this version of pluggy still works with current versions of pytest :)

**Comment by nicoddemus** [comment]
Oh duh right. 👍

**Pull request merged**
