### PR TITLE
Adjust stacklevel of implprefix warning

### LINKED ISSUE #166: Adjust the implprefix DeprecationWarning's stack level
Hi!

In #144 a deprecation warning was added for usage of the `implprefix` argument.

However the `warnings.warn()` call doesn't set a `stacklevel`, which means when the warning is output, the blamed line is in pluggy, rather than the plugin that's using `implprefix`. For example:
https://travis-ci.org/mozilla/treeherder/jobs/409417404#L895

Passing `stacklevel=2` would make it clearer as to where the issue lies, and also mean the correct module path can be referenced in eg pytest's `filterwarnings` (for downstream projects who enable warnings/deprecation warnings as errors).

Many thanks :-)

CC @tgoodlet

### PR DESCRIPTION
**Pull request by crazymerlyn**
Fixes #166.

### CODE REVIEW

**Comment by crazymerlyn** [comment]
The build is failing due to a recent [change](https://github.com/pytest-dev/pytest/pull/4104/commits/e0f6fce9e9213d5beda7f54e800a72ac95cbb3b6#diff-f08479569882d0799350ec99c3b8a05eR158) in pytest which adds a wrapper for `warnings.warn` function for python 2 (thus, changing the stack). Not sure what the best solution is here.
Adding a simple `if 'stacklevel' in kwargs: kwargs['stacklevel'] += 1` in the wrapper function could work.

**Comment by tgoodlet** [comment]
@crazymerlyn thanks for the PR :+1:!
@nicoddemus might know the right tweak to make.

**Comment by nicoddemus** [comment]
> Adding a simple if 'stacklevel' in kwargs: kwargs['stacklevel'] += 1 in the wrapper function could work.

Oh indeed, good catch. What do you think @asottile?

**Comment by asottile** [comment]
> > Adding a simple if 'stacklevel' in kwargs: kwargs['stacklevel'] += 1 in the wrapper function could work.
> 
> Oh indeed, good catch. What do you think @asottile?

oh! I see what you're saying now -- I was wracking my brain to figure out what was meant here.

```python
if isinstance(kwargs.get('stacklevel'), int):
    kwargs['stacklevel'] += 1
```

might be safer

probably PR that to pytest and we can get it into 3.9.2?

**Comment by crazymerlyn** [comment]
> ```python
> if isinstance(kwargs.get('stacklevel'), int):
>     kwargs['stacklevel'] += 1
> ```
> 
> might be safer
> 
> probably PR that to pytest and we can get it into 3.9.2?

Yeah, that seems better. But while we are on this, I think stacklevel also needs to be changed if it is not present in kwargs. The default value is 1. So, if somebody uses recwarn in python2.7, the warning will present itself at the wrapper function rather than the line causing the warning.
How about this:
```python
if isinstance(kwargs.get('stacklevel'), int):
    kwargs['stacklevel'] += 1
elif 'stacklevel' not in kwargs:
    kwargs['stacklevel'] = 2
```

**Comment by asottile** [comment]
ah in that case even easier:

```python
kwargs.setdefault('stacklevel', 1)
kwargs['stacklevel'] += 1
```

**Comment by asottile** [comment]
hmm yeah this is probably the `__warningregistry__` bits.  link your branch? I'll poke at it since I broke this :sob:

**Comment by nicoddemus** [comment]
> I'll poke at it since I broke this 

Heh, that's all good and part of the game 😁

**Comment by crazymerlyn** [comment]
@asottile https://github.com/crazymerlyn/pytest/tree/fix_recwarn_stacklevel.

**Comment by asottile** [comment]
not pretty, but at least this is throwaway :'( https://github.com/pytest-dev/pytest/pull/4192

**Comment by asottile** [comment]
sorry about the trouble again, thanks for the report! 🎉

**Comment by tgoodlet** [comment]
@nicoddemus good to go here yah?

**Comment by asottile** [comment]
yah!

**Comment by edmorley** [comment]
Many thanks!

**Pull request merged**
