### PR TITLE
Preparing release 0.8.0

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by tgoodlet** [comment]
We're cool with jumping to `0.8.0` already eh?

**Comment by nicoddemus** [comment]
It has been awhile since the latest release, and we don't have any pending PRs to include into the new release, so I thought why not? 😁

**Comment by tgoodlet** [comment]
@nicoddemus coolz. I'm down. I guess we'll do the `__mutlicall__` removal in `1.0` eh?

**Comment by nicoddemus** [comment]
:tada:

**Pull request merged**
