### PR TITLE
Add changelog for #199

### PR DESCRIPTION
**Pull request by asottile**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks @asottile!

**Comment by nicoddemus** [comment]
> ERROR: Error installing 'file:///home/travis/build/pytest-dev/pluggy': editable mode is not supported for pyproject.toml-style projects. pip is processing this project as pyproject.toml-style because it has a pyproject.toml file. Since the project has a setup.py and the pyproject.toml has no "build-backend" key for the "build_system" value, you may pass --no-use-pep517 to opt out of pyproject.toml-style processing. See PEP 517 for details on pyproject.toml-style projects.

*sigh*

**Comment by asottile** [comment]
lolrip

**Comment by asottile** [comment]
I fixed the installation error by avoiding installation.  I don't have the merge bit here, heh

**Comment by nicoddemus** [comment]
Thanks!

**Comment by nicoddemus** [comment]
I will prepare the next release tomorrow. 👍

**Pull request merged**
