### PR TITLE
Handle first result with None results

### PR DESCRIPTION
**Pull request by tgoodlet**
Addresses #68...

If you guys are happy with this I'll push up a patch release `0.5.1`...

### CODE REVIEW

**Comment by RonnyPfannschmidt** [comment]
at first glance i wonder if that test should trigger the behaviour, i was under the impression lack of plug-ins should trigger it

**Comment by tgoodlet** [comment]
That test definitely gets the exact same error so the fix should handle that case as well.
I can add another test for that case as well.

**Comment by RonnyPfannschmidt** [comment]
indeed https://github.com/pytest-dev/pluggy/blob/master/pluggy/callers.py#L92

so firstresult shortcuts, and there should always be zero or one results

**Comment by tgoodlet** [comment]
@RonnyPfannschmidt added that second test as well.

**Comment by tgoodlet** [comment]
haha wow totally broke it..

**Comment by tgoodlet** [comment]
there finally..

@nicoddemus just waiting on your stamp of approval 😄

**Comment by tgoodlet** [comment]
Thanks @asottile!

Once #70 is reviewed I'll push up the release 👍

**Pull request merged**
