### PR TITLE
Preparing release 0.10.0

### PR DESCRIPTION
**Pull request by nicoddemus**

### CODE REVIEW

**Comment by nicoddemus** [comment]
Can we release this now @asottile, or would you rather wait until tomorrow as you have mentioned elsewhere?

**Comment by asottile** [comment]
I'm about to jump on a plane, but hell what's the worst that could go wrong :shipit:

(now is fine!)

**Comment by nicoddemus** [comment]
No rush, we can push the tag tomorrow. 😁

**Comment by nicoddemus** [comment]
`0.10.0` released! 🎉

**Pull request merged**
